### PR TITLE
Do not block whole page while syncing

### PR DESCRIPTION
**Pull request by ycdesu**
Currently we block the whole page when the server is syncing. But actually we don't have to invoke sync API for some tabs, like strategy. Therefore, I remove the blocking dialog. We should be able to open the strategy page even if the syncing operation is not done yet.

The first time we enter the bbgo frontend page, it invokes the asynchronous sync API first. When we click the order or trade tab, it will query the orders/trades from bbgo API. It's reasonable not to receive whole data since the orders and trades are inserted anytime. it's not possible to always have latest data if bbgo only provides REST API.

So the logic is the same as previous implementation. 

Also, you can trigger the syncing anytime by click the sync button #715

### CODE REVIEW

**Comment by c9s** [comment]
@ycdesu can we show the sync status somewhere?

**Review by c9s — APPROVED** [review]

**Comment by ycdesu** [comment]
> @ycdesu can we show the sync status somewhere?

@c9s if it's syncing, I can disable the sync button and modify the button text to syncing. How about that?

**Comment by ycdesu** [comment]
@c9s could you review it again? I add the sync status to the button, and will fetch the status every 2 seconds.

**Review by c9s — APPROVED** [review]
thanks!!

**Pull request merged**
