### PR TITLE
refine auth message

### PR DESCRIPTION
**Pull request by tony1223**
refine auth message

### CODE REVIEW

**Comment by tony1223** [comment]
polygon:0xEE44aC234b5de7d369a398DB6f5C5A4856f0524e

**Review by c9s — APPROVED** [review]

**Comment by tony1223** [comment]
polygon:0xAb5801a7D398351b8bE11C439e05C5B3259aeC9

**Comment by tony1223** [comment]
polygon:0xEE44aC234b5de7d369a398DB6f5C5A4856f0524e

**Comment by tony1223** [comment]
`polygon:0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B`

**Pull request merged**
