### PR TITLE
Improve backtest report ui

### PR DESCRIPTION
**Pull request by ksidenko**
Updated visualization

image

### CODE REVIEW

**Comment by ksidenko** [comment]
@c9s hi!
In orders data there are order dublicates. I don't why. Can you check it?

**Comment by ksidenko** [comment]
polygon:0xB947e83C893F115037557d559dCA76aF6d612271

**Comment by ksidenko** [comment]
@c9s another thing, that is important, but I don't know how I can do it, is pass custom strategy params to backtest report. Have you any advise?

**Comment by c9s** [comment]
> @c9s hi! In orders data there are order dublicates. I don't understand why. Can you check it?

Are these order ids different? or they have different status?

I will also check this later.

**Comment by c9s** [comment]
> 

You can check pkg/cmd/backtest.go LINE 505, I think we can render the config file into a JSON file.

**Comment by c9s** [comment]
> another thing, that is important, but I don't know how I can do it, is pass custom strategy params to backtest report. Have you any advise?

You can check pkg/cmd/backtest.go LINE 505, I think we can render the config file into a JSON file.

**Review by c9s — APPROVED** [review]

**Comment by c9s** [comment]
neat!

**Pull request merged**
