### PR TITLE
add yaml tag for mapping basic risk control order executor.

### PR DESCRIPTION
**Pull request by crossgate10**
add yaml tag for mapping basic risk control order executor.

### CODE REVIEW

**Comment by c9s** [comment]
just to confirm is this a bug fix or just attaching the tag?

**Review by c9s — APPROVED** [review]

**Comment by crossgate10** [comment]
I found this issue when I'm debugging backtest step by step.
the value set correct in yaml, but not mapping, so I just attaching the tag to make it work.

**Comment by c9s** [comment]
thanks!

**Comment by c9s** [comment]
by the way. give me your metamask address, I will send you some BBG tokens

**Pull request merged**
