### PR TITLE
feat: add private strategy demo trading-gpt

### PR DESCRIPTION
**Pull request by yubing744**
Trading-GPT is a trading bot based on [bbgo](https://github.com/c9s/bbgo) and [ChatGPT](https://github.com/yubing744/chatgpt-go). I think this is a good example of a private bbgo strategy.

### CODE REVIEW

**Comment by yubing744** [comment]
My polygon address:

```
polygon:0x6D41E23356eF0190BCde4d1fCC03d509Fc5A10c9
```

**Comment by yubing744** [comment]
polygon:0x6D41E23356eF0190BCde4d1fCC03d509Fc5A10c9

**Comment by c9s** [comment]
@yubing744 can you do a rebase? your PR seems like contains some other commits that is in the main branch

**Comment by c9s** [comment]
@yubing744 in the repo https://github.com/yubing744/trading-gpt, actually you can use bbgo as a module, not a git submodule. 

see this https://github.com/c9s/bbgo/blob/main/doc/topics/developing-strategy.md

and this https://github.com/c9s/bbgo#write-your-own-private-strategy

**Comment by c9s** [comment]
You can also take a look at this template repo: https://github.com/narumiruna/bbgo-template

**Comment by yubing744** [comment]
> 

Ok, I'll rebase the master branch later

**Comment by yubing744** [comment]
> @yubing744 in the repo https://github.com/yubing744/trading-gpt, actually you can use bbgo as a Go module, not a git submodule.
> 
> see this https://github.com/c9s/bbgo/blob/main/doc/topics/developing-strategy.md
> 
> and this https://github.com/c9s/bbgo#write-your-own-private-strategy

I introduced it in the form of a sub-module because I modified the code of the OKEX exchange and added the function of placing orders in the margin mode.

**Comment by yubing744** [comment]
> @yubing744 can you do a rebase? your PR seems like contains some other commits that is in the main branch

Ok, I'll rebase the master branch later

**Comment by yubing744** [comment]
@c9s I have rebased this branch.

**Comment by c9s** [comment]
@yubing744 If possible, could you submit a PR for the OKex problem that you have met? thank you~

**Review by c9s — APPROVED** [review]

**Comment by yubing744** [comment]
> @yubing744 If possible, could you submit a PR for the OKex problem that you have met? thank you~

OK

**Pull request merged**
