### PR TITLE
Grid panel draft

### PR DESCRIPTION
**Pull request by jundesu**
I mocked the API response according to your reply (https://github.com/c9s/bbgo/issues/643#issuecomment-1152888832). I will refactor the component into smaller components in another pull request.

image

### CODE REVIEW

**Comment by jundesu** [comment]
```
polygon:0xb8E5080eCa42E09064824a8aaae18F7433e33A56
```

**Review by c9s — APPROVED** [review]
Looks good to me! thanks!

**Comment by c9s** [comment]
@jundesu could you please also place multiple panels in the same page? so that we can check the padding and margin between each panel.

**Comment by c9s** [comment]
425 BBG sent https://polygonscan.com/tx/0xaf9293ce45076de16f9f1169643ae6422d95845c18c2e5151976f1b13e15beb2

**Pull request merged**
